version: '3'
services:
  influxdb:
    image: "quay.io/influxdb/influxdb:2.0.0-beta"
    ports:
      - "8086:8086"
      - "9999:9999"
    environment:
      - INFLUXDB_DB=sensor
      - INFLUXDB_USER=guest
      - INFLUXDB_USER_PASSWORD=supersecretpassword
  apiserver:
    image: "oliviermichaelis/apiserver:dev"
    build:
      context: .
      dockerfile: cmd/apiserver/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SECRET_PATH=/credentials
      - INFLUX_SERVICE_URL=influxdb
      - INFLUX_SERVICE_PORT=8086
    volumes:
    - ./test:/credentials

