version: '3'
services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=sensor
      - INFLUXDB_USER=guest
      - INFLUXDB_USER_PASSWORD=supersecretpassword
