version: '3'
services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=sensor
      - INFLUXDB_USER=guest
      - INFLUXDB_USER_PASSWORD=supersecretpassword
  apiserver:
    image: "oliviermichaelis/apiserver:dev"
    build:
      context: .
      dockerfile: cmd/apiserver/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - INFLUX_SERVICE_URL=localhost
      - INFLUX_SERVICE_PORT=8086
      - INFLUX_SECRET_PATH=/test/influxdb
      - STATION_ID=test
    volumes:
    - ./test:/test

