apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "helm.fullname" . }}-dwd
  labels:
{{ include "helm.labels" . | indent 4 }}
spec:
  schedule: "*/10 * * * *"
#  ttlSecondsAfterFinished: 300
#  selector:
#    matchLabels:
#      app.kubernetes.io/name: {{ include "helm.name" . }}
#      app.kubernetes.io/instance: {{ .Release.Name }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "helm.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          {{- with .Values.dwd.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.dwd.image.repository }}:{{ .Values.dwd.image.tag }}"
            imagePullPolicy: {{ .Values.dwd.image.pullPolicy }}
            env:
            - name: STATION_ID
              value: {{ .Values.dwd.env.STATION_ID | quote}}
            resources:
              {{- toYaml .Values.dwd.resources | nindent 14 }}
          restartPolicy: OnFailure
