# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-producer:
    docker:
      - image: circleci/golang:1.13.1
      - image: rabbitmq:latest
    working_directory: /go/src/github.com/oliviermichaelis/home-sensor
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run: go get -t "github.com/d2r2/go-i2c"
      - run: go get -t "github.com/d2r2/go-bsbmp"
      - run: go get -t "github.com/d2r2/go-logger"
      - run: go get -t "github.com/streadway/amqp"
      - run: go build -ldflags="-s -w" -v ./...   # Linker flags to reduce binary filesize. Stripping debug information
      - run: go test -v ./...
      - persist_to_workspace:
          root: /go/src/github.com/oliviermichaelis/home-sensor
          paths:
            - producer

  push-producer:
    docker:
      - image: circleci/buildpack-deps
    environment:
      - IMAGE_NAME: oliviermichaelis/producer
      - TAG: 0.$CIRCLE_BUILD_NUM
    working_directory: /go/src/github.com/oliviermichaelis/home-sensor
    steps:
      - attach_workspace:
          at: /go/src/github.com/oliviermichaelis/home-sensor
      - setup_remote_docker
      - run: docker build -f cmd/producer/Dockerfile -t $IMAGE_NAME:$TAG ./cmd/producer/
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-producer
      - push-producer:
          requires:
            - build-producer
          filters:
            branches:
              only: master