# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1
      - image: rabbitmq:latest
      - image: influxdb:1.7.8
        environment:
          INFLUXDB_USER: telegraf
          INFLUXDB_USER_PASSWORD: secretpassword
    environment:
      - RABBITMQ_SECRET_PATH: /go/src/github.com/oliviermichaelis/home-sensor/test/rabbitmq
      - INFLUX_SECRET_PATH: /go/src/github.com/oliviermichaelis/home-sensor/test/influxdb
      - RABBITMQ_SERVICE_URL: localhost
    working_directory: /go/src/github.com/oliviermichaelis/home-sensor
    steps:
      - checkout
      - run: go get -t "github.com/d2r2/go-i2c" "github.com/d2r2/go-logger" "github.com/d2r2/go-bsbmp" "github.com/streadway/amqp" "github.com/influxdata/influxdb1-client/v2"
      - run: go build -ldflags="-s -w" -v ./...   # Linker flags to reduce binary filesize. Stripping debug information
      - run: go test -v ./...
  push-docker:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - IMAGE_NAME_PRODUCER: oliviermichaelis/producer
      - IMAGE_NAME_CONSUMER: oliviermichaelis/consumer
    steps:
      - checkout
      - run: |
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
      - run: |
          sudo apt-get install docker-ce=5:19.03.3~3-0~ubuntu-xenial docker-ce-cli=5:19.03.3~3-0~ubuntu-xenial qemu-user-static i2c-tools
          docker version
          mkdir -p ~/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
          mv buildx-v0.3.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
          chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: |
          docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
          docker buildx create --name multiarch --platform linux/amd64,linux/arm/v7
          docker buildx use multiarch
      - run: |
          TAG=0.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker buildx build --platform linux/arm/v7,linux/amd64 -t $IMAGE_NAME_PRODUCER:$TAG --push -f cmd/producer/Dockerfile .
          docker buildx build --platform linux/arm/v7,linux/amd64 -t $IMAGE_NAME_CONSUMER:$TAG --push -f cmd/consumer/Dockerfile .
workflows:
  version: 2
  build-test-push:
    jobs:
      - build
      - push-docker:
          requires:
            - build
          filters:
            branches:
              only: master