# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-producer:
    docker:
      - image: circleci/golang:1.13.1
      - image: rabbitmq:latest
    working_directory: /go/src/github.com/oliviermichaelis/home-sensor
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run: go get -t "github.com/d2r2/go-i2c"
      - run: go get -t "github.com/d2r2/go-bsbmp"
      - run: go get -t "github.com/d2r2/go-logger"
      - run: go get -t "github.com/streadway/amqp"
      - run: go build -ldflags="-s -w" -v ./...   # Linker flags to reduce binary filesize. Stripping debug information
      - run: go test -v ./...
#  push-producer:
#    docker:
#      - image: circleci/golang:1.13.1
#    environment:
#      - IMAGE_NAME: oliviermichaelis/producer
#    working_directory: /go/src/github.com/oliviermichaelis/home-sensor
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run: |
#          TAG=0.$CIRCLE_BUILD_NUM
#          docker build -f cmd/producer/Dockerfile -t $IMAGE_NAME:$TAG ./cmd/producer/
#          docker login -u $DOCKER_USER -p $DOCKER_PASS
#          docker push oliviermichaelis/producer:$TAG
  push-producer:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - IMAGE_NAME: oliviermichaelis/producer
#    working_directory: /go/src/github.com/oliviermichaelis/home-sensor
    steps:
      - run: apt-get update && apt-get install -y g
      - checkout
      - run:
          name: Install latest Docker
          command: |
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install docker-ce

            docker version

            mkdir -p ~/.docker/cli-plugins
            wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
            mv buildx-v0.3.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
            chmod a+x ~/.docker/cli-plugins/docker-buildx
#      - run: |
#          sudo apt-get remove docker docker-engine docker.io runc
#          sudo apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common
#          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
#          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
#          sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io
#          sudo docker run hello-world
#      - run: |
#          DOCKER_BUILDKIT=1
#          docker build --platform=local -o . git://github.com/docker/buildx
#          mv buildx ~/.docker/cli-plugins/docker-buildx
      - run: |
          docker buildx ls
          docker buildx create --name newbuilder
          docker buildx use newbuilder
      - run: |
          TAG=0.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker buildx build --platform linux/arm/v7,linux/amd64 --push -t $IMAGE_NAME:$TAG  ./cmd/producer/
workflows:
  version: 2
  build-test-push:
    jobs:
      - build-producer
      - push-producer:
          requires:
            - build-producer
          filters:
            branches:
              only: master