# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-producer:
    docker:
      - image: circleci/golang:1.13.1
      - image: rabbitmq:latest
    working_directory: /go/src/github.com/oliviermichaelis/home-sensor
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run: go get -t "github.com/d2r2/go-i2c"
      - run: go get -t "github.com/d2r2/go-bsbmp"
      - run: go get -t "github.com/d2r2/go-logger"
      - run: go get -t "github.com/streadway/amqp"
      - run: go build -ldflags="-s -w" -v ./...   # Linker flags to reduce binary filesize. Stripping debug information
      - run: go test -v ./...
  push-producer:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - IMAGE_NAME: oliviermichaelis/producer
    steps:
      - run: |
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
      - run: |
          sudo apt-get install docker-ce=5:19.03.3~3-0~ubuntu-xenial docker-ce-cli=5:19.03.3~3-0~ubuntu-xenial qemu-user-static
          docker version
          mkdir -p ~/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
          mv buildx-v0.3.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
          chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: |
          docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
          docker buildx create --name multiarch --platform linux/amd64,linux/arm/v7
          docker buildx use multiarch
      - checkout
      - run: |
          TAG=0.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker buildx build --platform linux/arm/v7,linux/amd64 -t $IMAGE_NAME:$TAG --push ./cmd/producer/
workflows:
  version: 2
  build-test-push:
    jobs:
      - build-producer
      - push-producer:
          requires:
            - build-producer
          filters:
            branches:
              only: master