# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

producer:
  image:
    repository: oliviermichaelis/producer
    tag: 0.41
    pullPolicy: IfNotPresent
  i2c:
    path: /dev/i2c-1
  rabbitmq:
    user: guest
    url: rabbitmq-ha.default.svc.cluster.local
    port: 5672
    queue: sensor
    exchange: sensor
  secretName: rabbitmq-ha
  volume:
    mountPath: /passwords
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  nodeSelector:
    sensor: "yes"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi



tolerations: []

affinity: {}
